version: '{build}'
shallow_clone: true

configuration:
  - Debug
  - Release

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_GENERATOR: "MinGW Makefiles"
    CXX_PATH: 'C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_GENERATOR: "MinGW Makefiles"
    CXX_PATH: 'C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_GENERATOR: "MinGW Makefiles"
    CXX_PATH: 'C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_GENERATOR: "MinGW Makefiles"
    CXX_PATH: 'C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CMAKE_GENERATOR: "Visual Studio 15 2017"
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_GENERATOR: "Visual Studio 14 2015"

matrix:
  fast_finish: true
  

install:
  # git bash conflicts with MinGW makefiles
  - if "%CMAKE_GENERATOR%"=="MinGW Makefiles" (set "PATH=%PATH:C:\Program Files\Git\usr\bin;=%")
  - if not "%CXX_PATH%"=="" (set "PATH=%PATH%;%CXX_PATH%")
  - git submodule update --init --recursive


build_script:
  - md _build -Force
  - cd _build
  - echo %configuration%
  - cmake -G "%CMAKE_GENERATOR%" "-DCMAKE_BUILD_TYPE=%configuration%" -DBUILD_TESTING=ON ..
  - cmake --build . --config %configuration%

test_script:
  - ctest -C %configuration% --timeout 300 --output-on-failure
